coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "crates/**/tests/**"
  - "crates/**/benches/**"
  - "crates/benchmark/**"
  - "crates/benchmark-suite/**"
  - "crates/*testsuite*/**"
  - "crates/testsuite-common/**"
