[package]
name = "jsonschema-testsuite-magnus"
publish = false
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "jsonschema_testsuite_magnus"
crate-type = ["cdylib"]
test = false

[dependencies]
jsonschema = { path = "../jsonschema", features = ["macros", "magnus"] }
magnus = { version = "0.8", features = ["rb-sys"] }
serde_json.workspace = true
testsuite = { package = "jsonschema-testsuite", path = "../jsonschema-testsuite" }

[lints]
workspace = true
