[package]
name = "jsonschema-testsuite-pyo3"
publish = false
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "jsonschema_testsuite_pyo3"
crate-type = ["cdylib"]
test = false

[dependencies]
jsonschema = { path = "../jsonschema", features = ["macros", "pyo3"] }
serde_json.workspace = true
pyo3 = { version = "0.29", features = ["extension-module"] }
testsuite = { package = "jsonschema-testsuite", path = "../jsonschema-testsuite" }

[lints]
workspace = true
