#!/usr/bin/env bash
# Regenerates the checked-in corpus TSVs that the test suite reads. Not run by CI.
#
#   (no arguments)     throwaway local cluster -> jsonb-corpus.tsv
#   --big-endian       emulated s390x server   -> jsonb-corpus-be.tsv
#   --bench-fixtures   the benchmark instances -> crates/benchmark/data/*.jsonb
#   --check-versions   one container per major version, reports whether their bytes agree
#
# `--big-endian` needs `docker run --privileged tonistiigi/binfmt --install s390x` once per boot.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES="$ROOT/crates/jsonschema-value/tests/fixtures"
INPUT="$FIXTURES/jsonb-corpus-input.jsonl"
READER_ONLY="$FIXTURES/jsonb-corpus-reader-only.jsonl"
OUTPUT="$FIXTURES/jsonb-corpus.tsv"
BE_OUTPUT="$FIXTURES/jsonb-corpus-be.tsv"

PGDATA=""
STARTED_CONTAINERS=()

cleanup() {
    if [ -n "$PGDATA" ]; then
        pg_ctl -D "$PGDATA" -m immediate stop >/dev/null 2>&1 || true
        rm -rf "$PGDATA"
    fi
    local container
    # Expanding an empty array under `set -u` aborts on bash 3.2, which is what macOS ships,
    # and this runs from the EXIT trap of the no-argument path where nothing was ever appended.
    for container in ${STARTED_CONTAINERS[@]+"${STARTED_CONTAINERS[@]}"}; do
        docker stop -t 5 "$container" >/dev/null 2>&1 || true
    done
}
trap cleanup EXIT

# TRUNCATE leaves exactly one live tuple on the page, so `lp_len > 0` matches only it. `:'json'`
# is psql's quoted-literal substitution, and expands under `-f -` but not under `-c`.
fixture_row() {
    local json="$1"
    local captured text hex
    captured="$("${PSQL[@]}" -v json="$json" -f - <<'SQL'
TRUNCATE jb;
INSERT INTO jb VALUES (:'json'::jsonb);
SELECT j::text FROM jb;
SELECT encode(t_data, 'hex') FROM heap_page_items(get_raw_page('jb', 0)) WHERE lp_len > 0;
SQL
)"
    text="$(sed -n '1p' <<<"$captured")"
    hex="$(sed -n '2p' <<<"$captured")"
    printf '%s\t%s\t%s\n' "$json" "$text" "$hex"
}

# The stored bytes for one instance, without its rendered text.
capture_hex() {
    "${PSQL[@]}" -v json="$1" -f - <<'SQL'
TRUNCATE jb;
INSERT INTO jb VALUES (:'json'::jsonb);
SELECT encode(t_data, 'hex') FROM heap_page_items(get_raw_page('jb', 0)) WHERE lp_len > 0;
SQL
}

# Writes the corpus read over the current `PSQL` connection to $1, stamped with the version $2.
generate_tsv() {
    local out_file="$1" pg_version="$2"
    {
        echo "# generated by tools/gen-jsonb-fixtures.sh against PostgreSQL $pg_version — do not edit by hand"
        while IFS= read -r line; do
            fixture_row "$line"
        done <"$INPUT"
        echo "# reader-only below this line: numbers beyond f64, byte-equality not asserted"
        while IFS= read -r line; do
            fixture_row "$line"
        done <"$READER_ONLY"
    } >"$out_file"
}

setup_schema() {
    "${PSQL[@]}" -f - <<'SQL'
CREATE EXTENSION pageinspect;
CREATE TABLE jb (j jsonb);
ALTER TABLE jb ALTER COLUMN j SET STORAGE PLAIN;
SQL
}

run_local() {
    # A socket path under a long working directory can exceed the 107-byte limit; use TCP.
    local port
    port="$(python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1])')"

    PGDATA="$(mktemp -d)"
    local log="$PGDATA/server.log"

    initdb -D "$PGDATA" -U postgres --auth=trust -E UTF8 --no-sync >/dev/null
    pg_ctl -D "$PGDATA" -o "-h 127.0.0.1 -p $port -k ''" -l "$log" start -w >/dev/null

    export PGCLIENTENCODING=UTF8
    PSQL=(psql -h 127.0.0.1 -p "$port" -U postgres -Atq)

    setup_schema
    local pg_version
    pg_version="$("${PSQL[@]}" -c "SHOW server_version;")"
    generate_tsv "$OUTPUT" "$pg_version"
    echo "Wrote $OUTPUT (PostgreSQL $pg_version)" >&2
}

# The entrypoint runs its setup against a temporary instance first, so only the second
# "ready to accept connections" is the real server.
wait_for_container() {
    local container="$1" tries=0 ready_count
    # Long enough for an emulated s390x boot; returns as soon as the line appears.
    while ((tries < 600)); do
        ready_count="$(docker logs "$container" 2>&1 | grep -c "database system is ready to accept connections" || true)"
        if ((ready_count >= 2)); then
            return 0
        fi
        sleep 0.5
        tries=$((tries + 1))
    done
    echo "postgres in $container did not become ready in time" >&2
    return 1
}

# Stamps $OUTPUT's second line with the comma-separated versions in $1 that agreed, replacing
# any earlier stamp.
record_verification() {
    local joined="$1"
    local comment="# byte-identical output verified against PostgreSQL $joined on $(date +%Y-%m-%d)"
    local tmp
    tmp="$(mktemp)"
    {
        head -n 1 "$OUTPUT"
        echo "$comment"
        tail -n +2 "$OUTPUT" | grep -v '^# byte-identical output verified against '
    } >"$tmp"
    # `mv` would leave mktemp's 0600 mode on $OUTPUT; writing through keeps the original.
    cat "$tmp" >"$OUTPUT"
    rm -f "$tmp"
}

# The rows two captures must agree on: no version header, no provenance stamp.
data_rows() {
    grep -v '^#' "$1" || true
}

# Only the debian-based image is built for s390x; the alpine one used elsewhere here is not.
run_big_endian() {
    local container="jsonb-fixtures-pg-be-$$"
    echo "Starting postgres:17 on linux/s390x (emulated) ..." >&2
    docker run -d --rm --name "$container" --platform linux/s390x \
        -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=postgres \
        postgres:17 >/dev/null
    STARTED_CONTAINERS+=("$container")

    wait_for_container "$container"

    PSQL=(docker exec -i "$container" psql -U postgres -Atq)
    setup_schema
    local pg_version
    pg_version="$("${PSQL[@]}" -c "SHOW server_version;")"
    generate_tsv "$BE_OUTPUT" "$pg_version on s390x"
    echo "Wrote $BE_OUTPUT (PostgreSQL $pg_version, big-endian)" >&2
}

# The benchmark fixtures hold the container with the varlena header stripped, the shape
# `Jsonb::root` takes.
BENCH_FIXTURES=(
    fast_valid fast_invalid geojson geojson_invalid
    patient-example-d patient-example-d-invalid
)

run_bench_fixtures() {
    local data="$ROOT/crates/benchmark/data"
    local port
    port="$(python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1])')"
    PGDATA="$(mktemp -d)"
    initdb -D "$PGDATA" -U postgres --auth=trust -E UTF8 --no-sync >/dev/null
    pg_ctl -D "$PGDATA" -o "-h 127.0.0.1 -p $port -k ''" -l "$PGDATA/server.log" start -w >/dev/null
    export PGCLIENTENCODING=UTF8
    PSQL=(psql -h 127.0.0.1 -p "$port" -U postgres -Atq)
    setup_schema

    local name hex
    for name in "${BENCH_FIXTURES[@]}"; do
        hex="$(capture_hex "$(cat "$data/$name.json")")"
        python3 -c "import sys; b = bytes.fromhex(sys.argv[1]); h, n = (1, b[0] >> 1) if b[0] & 1 else (4, int.from_bytes(b[:4], 'little') >> 2); open(sys.argv[2], 'wb').write(b[h:n])" "$hex" "$data/$name.jsonb"
        echo "Wrote $data/$name.jsonb" >&2
    done
}

run_check_versions() {
    local versions=("$@")
    local workdir
    workdir="$(mktemp -d)"

    declare -A digests
    declare -A pg_versions

    local version container out_file
    for version in "${versions[@]}"; do
        container="jsonb-fixtures-pg-$version-$$"
        echo "Starting postgres:$version-alpine ..." >&2
        docker run -d --rm --name "$container" \
            -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=postgres \
            "postgres:$version-alpine" >/dev/null
        STARTED_CONTAINERS+=("$container")

        wait_for_container "$container"

        PSQL=(docker exec -i "$container" psql -U postgres -Atq)
        setup_schema
        pg_versions[$version]="$("${PSQL[@]}" -c "SHOW server_version;")"

        out_file="$workdir/$version.tsv"
        generate_tsv "$out_file" "${pg_versions[$version]}"
        # Excludes the header line, which names the version by design.
        digests[$version]="$(tail -n +2 "$out_file" | sha256sum | cut -d' ' -f1)"

        docker stop -t 5 "$container" >/dev/null
        echo "postgres:$version-alpine -> PostgreSQL ${pg_versions[$version]}, sha256=${digests[$version]}" >&2
    done

    echo
    printf '%-8s %-20s %s\n' "major" "postgres_version" "sha256(rows)"
    for version in "${versions[@]}"; do
        printf '%-8s %-20s %s\n' "$version" "${pg_versions[$version]}" "${digests[$version]}"
    done
    echo

    if [ ${#versions[@]} -eq 0 ]; then
        echo "--check-versions needs at least one major version" >&2
        exit 2
    fi
    local first_digest="${digests[${versions[0]}]}"
    local agree=1
    for version in "${versions[@]}"; do
        [ "${digests[$version]}" = "$first_digest" ] || agree=0
    done

    if [ "$agree" -eq 1 ]; then
        echo "All ${#versions[@]} versions agree."
        # A stale $OUTPUT would get a stamp asserting a comparison against contents nothing
        # captured, so it has to match the fresh rows before being stamped.
        if ! diff <(data_rows "$workdir/${versions[0]}.tsv") <(data_rows "$OUTPUT") >/dev/null; then
            echo "Captured rows do not match the checked-in $OUTPUT — the corpus is stale." >&2
            echo "Run $(basename "$0") with no arguments to regenerate it, then re-run --check-versions." >&2
            echo "Per-version TSVs kept for inspection: $workdir" >&2
            return 1
        fi
        local joined="${versions[0]}"
        for version in "${versions[@]:1}"; do
            joined+=", $version"
        done
        record_verification "$joined"
        rm -rf "$workdir"
        return 0
    fi
    echo "DISAGREEMENT across versions. Per-version TSVs kept for inspection: $workdir"
    return 1
}

if [ "${1:-}" = "--check-versions" ]; then
    shift
    run_check_versions "$@"
elif [ "${1:-}" = "--big-endian" ]; then
    run_big_endian
elif [ "${1:-}" = "--bench-fixtures" ]; then
    run_bench_fixtures
else
    run_local
fi
