name: Benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - name: jsonschema
            package: jsonschema
            features: "--features macros"
            benches: "--bench jsonschema --bench keywords --bench errors --bench location --bench metaschema --bench unevaluated_items --bench unevaluated_properties"
          - name: codegen
            package: jsonschema
            features: "--features macros"
            benches: "--bench codegen"
          - name: codegen-generate
            package: jsonschema-macros-core
            features: "--features bench"
            benches: "--bench generate"
          - name: referencing
            package: referencing
            features: ""
            benches: ""
    name: "Run benchmarks (${{ matrix.name }})"
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.name }}

      - run: cargo install cargo-codspeed --force

      - run: cargo codspeed build -p ${{ matrix.package }} ${{ matrix.features }} ${{ matrix.benches }}

      - uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run -p ${{ matrix.package }}
          mode: "instrumentation"
          token: ${{ secrets.CODSPEED_TOKEN }}
