name: Benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - name: jsonschema
            package: jsonschema
            features: "--features macros"
            benches: "--bench jsonschema --bench keywords --bench errors --bench location --bench metaschema --bench unevaluated_items --bench unevaluated_properties"
          - name: codegen
            package: jsonschema
            features: "--features macros"
            benches: "--bench codegen"
          - name: codegen-generate
            package: jsonschema-macros-core
            features: "--features bench"
            benches: "--bench generate"
          - name: referencing
            package: referencing
            features: ""
            benches: ""
          - name: canonicalize
            package: jsonschema
            features: ""
            benches: "--bench canonicalize"
    name: "Run benchmarks (${{ matrix.name }})"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ matrix.name }}

      - run: cargo install cargo-codspeed --force

      - run: cargo codspeed build -p ${{ matrix.package }} ${{ matrix.features }} ${{ matrix.benches }}

      - uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          run: cargo codspeed run
          mode: "instrumentation"
          token: ${{ secrets.CODSPEED_TOKEN }}
