name: Benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  rust:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo install cargo-codspeed

      - run: cargo codspeed build -p jsonschema -p referencing jsonschema registry anchor pointer subresources

      - uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run -p jsonschema -p referencing jsonschema registry anchor pointer subresources
          token: ${{ secrets.CODSPEED_TOKEN }}
