name: Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  fuzz:
    name: Fuzzing ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: ["builder", "validation", "referencing", "codegen", "canonical"]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Download previous corpus
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ./fuzz/corpus/${{ matrix.target }}
          key: ${{ runner.os }}-corpus-${{ matrix.target }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-corpus-${{ matrix.target }}-

      - run: cargo install cargo-fuzz --force

      - run: |
          mkdir -p fuzz/corpus/${{ matrix.target }}
          cargo +nightly fuzz run --release ${{ matrix.target }} fuzz/corpus/${{ matrix.target }} fuzz/seeds -- -dict=fuzz/dict -max_total_time=10800
