name: Rust Release

on:
  push:
    tags:
      - rust-v*

jobs:
  rust-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - run: cargo publish --manifest-path crates/jsonschema-referencing/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-value/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-regex/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-macros-core/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-macros/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-cli/Cargo.toml

      - name: Extract Version
        run: echo "version=${GITHUB_REF#refs/tags/rust-v}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          make_latest: false
          draft: true
          name: "[Rust] Release ${{ env.version }}"
