name: Rust Release

on:
  push:
    tags:
      - rust-v*

jobs:
  rust-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - run: cargo publish --manifest-path crates/jsonschema-referencing/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema/Cargo.toml

      - run: cargo publish --manifest-path crates/jsonschema-cli/Cargo.toml
